= MVP

Information about what is included in the MVP for {ProjectName} ({ProjectShortName}).

== Workflows

At its core the TSSC is an opinionated workflow used to delivery software from peoples heads to production. This section is a pictorial versions of that opinionated workflow.

[[tssc-abstract-workflows, TSSC Abstract Workflows]]
=== Abstract

When discussing methods for getting ideas from peoples heads to production groups often get lost in talking about technology and tools when the hard work is deciding on the abstract process, or workflow. This section has pictorial renderings of the TSSC opinionated "idea to production" workflow in an abstract form, that is without any specific technologies or tools.

==== Use

The usage of these diagrams is intended to be both used as is to spark discussion as to what your team's specific TSSC workflow will be without getting distracted by technology or tools. The intent being that a team can take the link:images/tssc_diagrams.drawio[Trusted Software Supply Chain (TSSC) diagrams draw.io source] and modify it to match the specific workflow the team agrees to. Then, copy that and fill in the technologies and tools, examples of which can be found in <<tssc-tech-specific-workflows>>.

[[NOTE]]
====
The draw.io source for the <<tssc-abstract-workflows>> can be found here, link:images/tssc_diagrams.drawio[tssc_diagrams.drawio].
====

[[tssc-abstract-workflow-high-level, TSSC Abstract Workflow High Level]]
==== High Level

A high level rendering of the TSSC workflow where the majority of steps are Predefined Procedures, that is they are placeholders for more complex sub workflows containing multiple Procedures, the details of which are defined in <<tssc-abstract-workflow-details>>. If something is needed that will fit on "one slide" this is it.

[[tssc-abstract-workflow-high-level-image, TSSC Abstract Workflow High Level Image]]
image::Trusted_Software_Supply_Chain_(TSSC)_-_Workflow_-_High_Level.png[alt="Trusted Software Supply Chain (TSSC) - Workflow - High Level ",title="Trusted Software Supply Chain (TSSC) - High Level ",caption="Workflow: ",link=images/Trusted_Software_Supply_Chain_(TSSC)_-_Workflow_-_High_Level.png]

[[tssc-abstract-workflow-details, TSSC Abstract Workflow Details]]
==== Detailed

If there is one artifact that defines what the TSSC is, this is it. This is the detailed opinionated workflow for delivering "ideas to production" as defined by and implemented by the TSSC.

[[tssc-abstract-workflow-details-image, TSSC Abstract Workflow Details Image]]
image::Trusted_Software_Supply_Chain_(TSSC)_-_Workflow_-_Details.png[alt="Trusted Software Supply Chain (TSSC) - Workflow - Details",title="Trusted Software Supply Chain (TSSC) - Details",caption="Workflow: ",link=images/Trusted_Software_Supply_Chain_(TSSC)_-_Workflow_-_Details.png]

[[tssc-tech-specific-workflows, TSSC Technology Specific Workflows]]
=== Technology Specific

This section contains technology specific renderings of the <<tssc-abstract-workflows>> for re-use and reference.

==== Backend Application - JavaEE
#TODO#

==== Frontend Application - JavaScript
#TODO#

== Tooling

The following table lists chosen tooling for the TSSC MVP implementation.  A separate document will be used to list all implementations as the progress moves forward.  See diagram for system architecture.

.Tooling by Workflow Implementation
[cols="a,a,a",options="header"]
|===
| Purpose
2+| Tools by Workflow Type

|
h| *Java (Backend)*
h| *JavaScript (Frontend)*

| Source Control 
2+| https://github.com/go-gitea/gitea[Gitea]

| Container Orchestration
2+| Red Hat OpenShift Container Platform 4 (OCP)

| Identity Management
2+| Red Hat Single Sign-On (RH SSO) (KeyCloak)

| Artifact Repository
2+| https://jfrog.com/open-source/[JFrog Artifactory]

| Image Registry
2+| Red Hat Quay (+ Clair)

| Continuous Integration
2+|
* Jenkins (https://github.com/rhtconsulting/tssc-jenkins[pipelines])
* Tekton (https://github.com/rhtconsulting/tssc-tekton[pipelines])

| Continuous Deployment
2+| https://argoproj.github.io/argo-cd/[ArgoCD]

| Security Static Code Analysis
| SonarQube
| SonarQube

| Linting Satic Code Analysis
| SonarQube
| SonarQube

| Unit Testing
| Junit
|
* TBD
** Mocha?
** Jest?
** ?

| Build
| Maven
| N/A

| Static Compliance Container Image Scanning
| OpenSCAP
| OpenSCAP

| Static Vulnerability Container Image Scanning
| OpenSCAP
| OpenSCAP

| UAT
| Cucumber
| Selenium

| Runtime Vulnerability Scanning
|
* TBD
** OWASP compliant (might be within CI tool)
|
* TBD
** OWASP compliant (might be within CI tool)

| Canary Testing
a| Selenium
a| Selenium

| Development Workflow (IDE)
a| TBD
a| TBD
|===

== Development Infrastructure

=== Sizing
.Containerized Tool Sizing
[cols="a,a,a,a",options="header"]
|===
| Tool
| CPUs
| Memory (GB)
| Sizing Source

| Red Hat SSO
| 2
| 2
| WAG (https://access.redhat.com/solutions/3217681[Capacity planning, Sizing guide, Performance Tuning or Benchmarks for RH-SSO]

| JFrog Artifactory OSS
| 4
| 4
| https://www.jfrog.com/confluence/display/JFROG/System+Requirements#SystemRequirements-RecommendedHardware[JFrog Artifactory Docs - Recommended Hardware]

| JFrog Artifactory OSS - DB (PostgreSQL)
| 2
| 2
| WAG since https://www.jfrog.com/confluence/display/JFROG/System+Requirements#SystemRequirements-RecommendedHardware[JFrog Artifactory Docs - Recommended Hardware] provides no recommendation

| Red Hat Quay - Operator Based
| 2
| 4
| https://access.redhat.com/documentation/en-us/red_hat_quay/3.2/html/deploy_red_hat_quay_-_basic/preparing_for_red_hat_quay_basic#prerequisites[Quay Docs - Preparing for Red Hat Quay Basic - Prerequisites],
https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploy_red_hat_quay_on_openshift_with_quay_setup_operator/architecture[Operator and Quay Architecture]

| Red Hat Quay - Operator Based - DB (Cruncy Data PostgrSQL)
| 2 / Operator Governed
| 8 / Operator Governed
| 

| Red Hat Clair
| 2
| 4
|

| Tekton
| Operator Governed
| Operator Governed
| https://openshift.github.io/pipelines-docs/docs/0.10.5/assembly_installing-pipelines.html[Tekton Pipelines Docs - Github Pages for Openshift 4]

| Jenkins Master
| 2
| 2
| WAG based on experince.

| Jenkins Works
| Variable
| Variable
| 

| ArgoCD
| 1
| 4
| Worker images are 50Mb in size, API server is extremely small.

| SonarQube
| 2
| 2
| WAG since https://docs.sonarqube.org/latest/requirements/hardware-recommendations/[SonarQube official docs] offers no suggestion

| SonarQube DB (PostgreSQL)
| 2
| 2
| WAG since https://docs.sonarqube.org/latest/requirements/hardware-recommendations/[SonarQube official docs] offers no suggestion

| Cucumber
| N/A (embedded in CI container)
| N/A (embedded in CI container)
|
|===

.Red Hat OpenShift Sizing
[cols="a,a,a,a,a,a",options="header"]
|===
| Node
| CPUs
| Memmory (GB)
| Disk (GB)
| AWS EC2 Instance Type
| Sizing Source

| Master 0
| 8
| 32
| 120
| m4.2xlarge
| https://docs.openshift.com/container-platform/4.3/scalability_and_performance/recommended-host-practices.html#master-node-sizing_[OCP 4 Docs - Master Node Sizing]

| Master 1
| 8
| 32
| 120
| m4.2xlarge
| https://docs.openshift.com/container-platform/4.3/scalability_and_performance/recommended-host-practices.html#master-node-sizing_[OCP 4 Docs - Master Node Sizing]

| Master 2
| 8
| 32
| 120
| m4.2xlarge
| https://docs.openshift.com/container-platform/4.3/scalability_and_performance/recommended-host-practices.html#master-node-sizing_[OCP 4 Docs - Master Node Sizing]

| Compute 0
| 8
| 32
| 120
| m4.2xlarge
| Based on Containerized Tool Sizing needs

| Compute 1
| 8
| 32
| 120
| m4.2xlarge
| Based on Containerized Tool Sizing needs

| Compute 2
| 8
| 32
| 120
| m4.2xlarge
| Based on Containerized Tool Sizing needs
|===
