[id="{ProjectNameID}-opinions", reftext="{ProjectShortName} Opinions"]
= {ProjectShortName} Opinions

The {ProjectName} {ProjectShortName} is an opinionated software development and deployment workflow. The key being, opinionated. Which means it is filled with opinions, some direct, some less so. This document is meant to capture all of those opinions which feed into the design and implementation of the {ProjectShortName}.

*  The CI tool used does not, and should not, matter

*  https://trunkbaseddevelopment.com/[Trunk based development], as opposed to
   -  https://nvie.com/posts/a-successful-git-branching-model/[git-flow]
   -  https://guides.github.com/introduction/flow/[GitHub Flow]

*  When creating merge requests, crate feature branches on forks rather then on the primary repository, just as things are done in large open source projects

*  The "Release Branch" is the branch that goes into production. This may be different from team to team.  There are many different naming conventions for a branch that goes to production (e.g. `main`, `trunk`, release branch, or "Release 1.0.3"). This documentation will use "Release branch" to refer to whichever branch(s) have the possibility of going all the way to production.

*  The minimum, and recommended, number of logical environments is
   - `N` number of development environments, one per active feature branch
   - Test
   - Production

[NOTE]
====
More Coming.
====
