[id="{ProjectNameID}-opinions", reftext="{ProjectShortName} Opinions"]
= {ProjectShortName} Opinions

The {ProjectName} {ProjectShortName} is an opinionated software development and deployment workflow. The key being, opinionated. Which means it is filled with opinions, some direct, some less so. This document is meant to capture all of those opinions which feed into the design and implementation of the {ProjectShortName}.

*  The CI tool used does not, and should not, matter

*  https://trunkbaseddevelopment.com/[Trunk based development], as opposed to
   -  https://nvie.com/posts/a-successful-git-branching-model/[git-flow]
   -  https://guides.github.com/introduction/flow/[GitHub Flow]

*  When creating merge requests, create feature branches on forks rather then on the primary repository, just as things are done in large open source projects

*  The "Release Branch" is the branch that goes into production. The term "main" will be used to refer to the release branch. The name of this branch may be different from team to team.  There are many different naming conventions for a branch that goes to production (e.g. "master", "trunk", "release", etc.) 

*  The minimum, and recommended, number of logical environments is
   - `N` number of development environments, one per active feature branch
   - Test
   - Production

* A "step runner" is the implementation of all the necessary work associated with common steps in a CI/CD pipeline. Examples of step runners include: package, tag source, unit test, etc. The implementation of the step runner is abstracted away from the user, and available as reusable modules via the step runner library.   

*  For UAT testbed infrastructure (e.g. Selenium Grid), such infrastructure, when possible, should be dynamically created on-demand (by infrastructure-as-code) using a step runner from the step runner library. There will be cases where UAT infrastructure already exists in-house. In such cases, the use of pre-existing/static infrastructure is a supported alternative for UAT testing.  For example, if your company already has an established deployment of selenium grid, that instance of selenium grid can be used rather than have the framework dynamically stand up additional instances.  


[NOTE]
====
More Coming.
====
